package com.example.infractionservice.web.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-07-08T14:51:08.229+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://SOAP.Web.infractionservice.example.com/", name = "InfractionSoapController")
@XmlSeeAlso({ObjectFactory.class})
public interface InfractionSoapController {

    @WebMethod
    @RequestWrapper(localName = "findById", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.infractionservice.web.soap.InfractionResponseDTO findById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.example.infractionservice.web.soap.InfractionResponseDTO> findAll()
;

    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.infractionservice.web.soap.InfractionResponseDTO save(

        @WebParam(name = "arg0", targetNamespace = "")
        com.example.infractionservice.web.soap.InfractionRequestDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findByMatricule", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindByMatricule")
    @ResponseWrapper(localName = "findByMatriculeResponse", targetNamespace = "http://SOAP.Web.infractionservice.example.com/", className = "com.example.infractionservice.web.soap.FindByMatriculeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.example.infractionservice.web.soap.InfractionResponseDTO> findByMatricule(

        @WebParam(name = "matricule", targetNamespace = "")
        java.lang.String matricule
    );
}
