package com.example.infractionservice.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-07-08T14:51:08.575+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "InfractionWS",
                  wsdlLocation = "file:/C:/Users/YOUSSEF/Downloads/Infractions/Radar-Service/src/main/resources/InfractionService.wsdl",
                  targetNamespace = "http://SOAP.Web.infractionservice.example.com/")
public class InfractionWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://SOAP.Web.infractionservice.example.com/", "InfractionWS");
    public final static QName InfractionSoapControllerPort = new QName("http://SOAP.Web.infractionservice.example.com/", "InfractionSoapControllerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/YOUSSEF/Downloads/Infractions/Radar-Service/src/main/resources/InfractionService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfractionWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/YOUSSEF/Downloads/Infractions/Radar-Service/src/main/resources/InfractionService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfractionWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfractionWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfractionWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InfractionWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfractionWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfractionWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InfractionSoapController
     */
    @WebEndpoint(name = "InfractionSoapControllerPort")
    public InfractionSoapController getInfractionSoapControllerPort() {
        return super.getPort(InfractionSoapControllerPort, InfractionSoapController.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfractionSoapController
     */
    @WebEndpoint(name = "InfractionSoapControllerPort")
    public InfractionSoapController getInfractionSoapControllerPort(WebServiceFeature... features) {
        return super.getPort(InfractionSoapControllerPort, InfractionSoapController.class, features);
    }

}
