package com.example.immatriculationservice.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-07-03T00:37:40.389+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "VehiculeWS",
                  wsdlLocation = "file:/C:/Users/youssef/Desktop/Infractions/Radar-Service/src/main/resources/VehiculeService.wsdl",
                  targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/")
public class VehiculeWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://SOAP.Web.immatriculationservice.example.com/", "VehiculeWS");
    public final static QName VehiculeSoapControllerPort = new QName("http://SOAP.Web.immatriculationservice.example.com/", "VehiculeSoapControllerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/youssef/Desktop/Infractions/Radar-Service/src/main/resources/VehiculeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VehiculeWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/youssef/Desktop/Infractions/Radar-Service/src/main/resources/VehiculeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VehiculeWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VehiculeWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehiculeWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VehiculeWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VehiculeWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VehiculeWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VehiculeSoapController
     */
    @WebEndpoint(name = "VehiculeSoapControllerPort")
    public VehiculeSoapController getVehiculeSoapControllerPort() {
        return super.getPort(VehiculeSoapControllerPort, VehiculeSoapController.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehiculeSoapController
     */
    @WebEndpoint(name = "VehiculeSoapControllerPort")
    public VehiculeSoapController getVehiculeSoapControllerPort(WebServiceFeature... features) {
        return super.getPort(VehiculeSoapControllerPort, VehiculeSoapController.class, features);
    }

}
