package com.example.immatriculationservice.web.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-07-03T00:37:40.286+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", name = "VehiculeSoapController")
@XmlSeeAlso({ObjectFactory.class})
public interface VehiculeSoapController {

    @WebMethod
    @RequestWrapper(localName = "findAll", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.example.immatriculationservice.web.soap.VehiculeResponseDTO> findAll()
;

    @WebMethod
    @RequestWrapper(localName = "findById", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.immatriculationservice.web.soap.VehiculeResponseDTO findById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.immatriculationservice.web.soap.VehiculeResponseDTO save(

        @WebParam(name = "arg0", targetNamespace = "")
        com.example.immatriculationservice.web.soap.VehiculeRequestDTO arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findByMatricule", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindByMatricule")
    @ResponseWrapper(localName = "findByMatriculeResponse", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.FindByMatriculeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.immatriculationservice.web.soap.VehiculeResponseDTO findByMatricule(

        @WebParam(name = "matricule", targetNamespace = "")
        java.lang.String matricule
    );

    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://SOAP.Web.immatriculationservice.example.com/", className = "com.example.immatriculationservice.web.soap.UpdateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.immatriculationservice.web.soap.VehiculeResponseDTO update(

        @WebParam(name = "arg0", targetNamespace = "")
        com.example.immatriculationservice.web.soap.VehiculeRequestDTO arg0
    );
}
